# Generated by Django 5.0.3 on 2024-03-10 17:28

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('video_file', models.FilePathField(path=pathlib.PurePosixPath('/home/steph/bird-watcher/bird_watcher/assets/videos'))),
                ('thumbnail_file', models.ImageField(upload_to=pathlib.PurePosixPath('/home/steph/bird-watcher/bird_watcher/assets/thumbnails'))),
                ('num_frames', models.IntegerField()),
                ('framerate', models.FloatField()),
                ('tags', models.ManyToManyField(default=[], related_name='videos', to='birdwatcher.tag')),
            ],
        ),
    ]
