# Generated by Django 5.0.3 on 2024-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdwatcher', '0002_alter_video_thumbnail_file_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.TextField(default='temporary_title'),
        ),
    ]
